version: '3'

name: beersup

services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=beersup
    volumes:
      - postgres-vol:/var/lib/postgresql/data

  backend:
    build:
      context: ./
      dockerfile: ./deployments/local/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CONFIG_FILE=./deployments/local/config.json

volumes:
  postgres-vol:
    driver: local
